.TH "include/Core.hpp" 3 "Tue Mar 17 2015" "Minautorus" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/Core.hpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include <SFML/Graphics\&.hpp>\fP
.br
\fC#include <chrono>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCore\fP"
.br
.RI "\fI\fBCore\fP game management\&. \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Minautorus from the source code\&.
