.TH "src/Core.cpp" 3 "Tue Mar 17 2015" "Minautorus" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/Core.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <Core\&.hpp>\fP
.br
\fC#include <Scene\&.hpp>\fP
.br
\fC#include <Menu\&.hpp>\fP
.br
\fC#include <InGame\&.hpp>\fP
.br
\fC#include <TextureManager\&.hpp>\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for Minautorus from the source code\&.
