.TH "include/Global.hpp" 3 "Tue Mar 17 2015" "Minautorus" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/Global.hpp \- All the macros and constante values\&.  

.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBDATA_PATH\fP   'data/'"
.br
.ti -1c
.RI "#define \fBIMG_PATH\fP   'img/'"
.br
.ti -1c
.RI "#define \fBSCREEN_WIDTH\fP   640"
.br
.ti -1c
.RI "#define \fBSCREEN_HEIGHT\fP   480"
.br
.ti -1c
.RI "#define \fBWIDTH\fP   640"
.br
.ti -1c
.RI "#define \fBHEIGHT\fP   480"
.br
.ti -1c
.RI "#define \fBBLOC_WIDTH\fP   16"
.br
.ti -1c
.RI "#define \fBBLOC_HEIGHT\fP   \fBBLOC_WIDTH\fP"
.br
.ti -1c
.RI "#define \fBNB_TILE_WIDTH\fP   ((\fBWIDTH\fP)/(\fBBLOC_WIDTH\fP))"
.br
.ti -1c
.RI "#define \fBNB_TILE_HEIGHT\fP   ((\fBHEIGHT\fP)/(\fBBLOC_HEIGHT\fP))"
.br
.in -1c
.SH "Detailed Description"
.PP 
All the macros and constante values\&. 


.PP
Definition in file \fBGlobal\&.hpp\fP\&.
.SH "Macro Definition Documentation"
.PP 
.SS "#define BLOC_HEIGHT   \fBBLOC_WIDTH\fP"

.PP
Definition at line 20 of file Global\&.hpp\&.
.SS "#define BLOC_WIDTH   16"

.PP
Definition at line 19 of file Global\&.hpp\&.
.SS "#define DATA_PATH   'data/'"

.PP
Definition at line 10 of file Global\&.hpp\&.
.SS "#define HEIGHT   480"

.PP
Definition at line 17 of file Global\&.hpp\&.
.SS "#define IMG_PATH   'img/'"

.PP
Definition at line 11 of file Global\&.hpp\&.
.SS "#define NB_TILE_HEIGHT   ((\fBHEIGHT\fP)/(\fBBLOC_HEIGHT\fP))"

.PP
Definition at line 23 of file Global\&.hpp\&.
.SS "#define NB_TILE_WIDTH   ((\fBWIDTH\fP)/(\fBBLOC_WIDTH\fP))"

.PP
Definition at line 22 of file Global\&.hpp\&.
.SS "#define SCREEN_HEIGHT   480"

.PP
Definition at line 14 of file Global\&.hpp\&.
.SS "#define SCREEN_WIDTH   640"

.PP
Definition at line 13 of file Global\&.hpp\&.
.SS "#define WIDTH   640"

.PP
Definition at line 16 of file Global\&.hpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Minautorus from the source code\&.
