.TH "include/InGame.hpp" 3 "Tue Mar 17 2015" "Minautorus" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/InGame.hpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include <SFML/Graphics\&.hpp>\fP
.br
\fC#include <Global\&.hpp>\fP
.br
\fC#include <Scene\&.hpp>\fP
.br
\fC#include <Map\&.hpp>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBInGame\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Minautorus from the source code\&.
