.TH "include/Map.hpp" 3 "Tue Mar 17 2015" "Minautorus" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/Map.hpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include <SFML/Graphics\&.hpp>\fP
.br
\fC#include <Global\&.hpp>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBTile\fP"
.br
.ti -1c
.RI "class \fBMap\fP"
.br
.RI "\fI\fBMap\fP generation and displaying\&. \fP"
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBTileType\fP { \fBGROUND\fP = 0, \fBWALL\fP = 0 }"
.br
.in -1c
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBTileType\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIGROUND \fP\fP
.TP
\fB\fIWALL \fP\fP
.PP
Definition at line 8 of file Map\&.hpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Minautorus from the source code\&.
