.TH "src/minautorus.cpp" 3 "Tue Mar 17 2015" "Minautorus" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/minautorus.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include <SFML/Graphics\&.hpp>\fP
.br
\fC#include <Core\&.hpp>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (int argc, char **argv)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main (int argc, char ** argv)"

.PP
Definition at line 8 of file minautorus\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Minautorus from the source code\&.
