.TH "include/Scene.hpp" 3 "Tue Mar 17 2015" "Minautorus" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/Scene.hpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include <SFML/Graphics\&.hpp>\fP
.br
\fC#include <Core\&.hpp>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBScene\fP"
.br
.RI "\fIAbstract class that describe a \fBScene\fP\&. \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Minautorus from the source code\&.
