.TH "include/TextureManager.hpp" 3 "Tue Mar 17 2015" "Minautorus" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/TextureManager.hpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include <unordered_map>\fP
.br
\fC#include <SFML/Graphics\&.hpp>\fP
.br
\fC#include <Global\&.hpp>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBTextureManager\fP"
.br
.RI "\fITexture loader\&. \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Minautorus from the source code\&.
