.TH "Tile" 3 "Tue Mar 17 2015" "Minautorus" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Tile \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Map\&.hpp>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "size_t \fBi\fP"
.br
.ti -1c
.RI "size_t \fBj\fP"
.br
.ti -1c
.RI "\fBTileType\fP \fBtype\fP"
.br
.ti -1c
.RI "bool \fBobstacle\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 14 of file Map\&.hpp\&.
.SH "Member Data Documentation"
.PP 
.SS "size_t Tile::i"

.PP
Definition at line 16 of file Map\&.hpp\&.
.SS "size_t Tile::j"

.PP
Definition at line 17 of file Map\&.hpp\&.
.SS "bool Tile::obstacle"

.PP
Definition at line 20 of file Map\&.hpp\&.
.SS "\fBTileType\fP Tile::type"

.PP
Definition at line 19 of file Map\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Minautorus from the source code\&.
